VECTORSTORE_PATH = "./vectorstore/vectorstore.joblib"
DOCUMENTS_PATH = "./documents"
AWS_REGION = "us-east-1"
EMBEDDING_MODEL = "amazon.titan-embed-text-v1"
AWS_S3_BUCKET = "bedrock-question-answer"
BEDROCK_TEXT_MODEL = "anthropic.claude-v2"