#!/bin/bash

echo "Enter AWS_ACCESS_KEY_ID:"
read AWS_ACCESS_KEY_ID
echo "Enter AWS_SECRET_ACCESS_KEY:"
read AWS_SECRET_ACCESS_KEY
echo "Enter AWS_DEFAULT_REGION:"
read AWS_DEFAULT_REGION

docker run -p 80:80 --env-file .env \
	-e QDRANT_URL=$QDRANT_URL \
	-e QDRANT_API_KEY=$QDRANT_API_KEY \
	-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
	-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
	app 